config/routes.rb
Rails.application.routes.draw do

    get "/offers/list", to:"offers#list",as: 'list_offer'
  resources :requests
  resources :offers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  get "/offers/:id/aprobado", to:"offers#aprobado",as: 'approb_offer'
  get "/offers/:id/no_aprobado", to:"offers#no_aprobado",as: 'non_approb_offer'
  get "/offers/:id/autorizado", to:"offers#autorizado",as: 'authotized_offer'
  get "/offers/:id/no_autorizado", to:"offers#no_autorizado",as: 'non_authotized_offer'
  get "/offers/:id/subido", to:"offers#subido",as: 'upload_offer'
  get "/offers/:id/monetizado", to:"offers#monetizado",as: 'monetized_offer'
  get "/offers/:id/afiliado", to:"offers#afiliado",as: 'afiliate_offer'
  get "/offers/:id/stop", to:"offers#stop",as: 'stop_offer'
  get "/offers/:id/destruido", to:"offers#destruido",as: 'destruido_offer'







end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord

end

app/models/request.rb
class Request < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.where(estado: 'aprobado').or(Offer.where(estado:'rechazado').or(Offer.where(estado: nil).or(Offer.where(estado:'autorizado').or(Offer.where(estado:'no_autorizado')))))
    @offer = Offer.new
  end

  def list
    @offers = Offer.where(estado: 'subido').or(Offer.where(estado:'afiliado').or(Offer.where(estado:'monetizado').or(Offer.where(estado:'stop'))))
    @offer = Offer.new
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @offersI = Offer.all
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_url, notice: 'Offer was successfully created.' }
        format.json { render :index, estado: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, estado: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :index, estado: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, estado: :unprocessable_entity }
      end
    end
  end

  def aprobado
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"aprobado")
     redirect_to offers_url
  end

  def destruido
    @offer = Offer.find(params[:id])
    @offer.destroy
    respond_to do |format|
      if @offer.estado=="aprobado"||@offer.estado=="rechazado"
        format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
        format.json { head :no_content }
      end
      format.html { redirect_to list_offer_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def no_aprobado
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"rechazado")
     redirect_to offers_url
  end

  def autorizado
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"autorizado")
     redirect_to offers_url
  end

  def no_autorizado
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"no_autorizado")
     redirect_to offers_url
  end

  def subido
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"subido")
     redirect_to list_offer_url
  end
  def monetizado
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"monetizado")
     redirect_to list_offer_url
  end
  def afiliado
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"afiliado")
     redirect_to list_offer_url
  end
  def stop
    @offer = Offer.find(params[:id])
    @offer.update(:estado =>"stop")
     redirect_to list_offer_url
  end
  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:estado, :agency, :tipo, :app, :os, :kpi, :geo, :price, :agencyLink, :oferta_des)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
    @request = Request.new

  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @requestsI = Request.all
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to requests_url, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to requests_url, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:estado, :agency, :tipo, :app, :os, :geo, :price, :agencyLink)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plataforma</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_for(offer) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="center">
  <div class="field">
    <%= f.label :agency %>
    <%= f.text_field :agency %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :app %>
    <%= f.text_field :app %>
  </div>

  <div class="field">
    <%= f.label :os %>
    <%= f.text_field :os %>
  </div>

  <div class="field">
    <%= f.label :kpi %>
    <%= f.text_field :kpi %>
  </div>

  <div class="field">
    <%= f.label :geo %>
    <%= f.text_field :geo %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :agencyLink %>
    <%= f.text_field :agencyLink %>
  </div>

  <div class="field">
    <%= f.label :oferta_des %>
    <%= f.text_field :oferta_des %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<div class= "bg">
<p id="notice"><%= notice %></p>

<style>
.btn-group .button {
     /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    cursor: pointer;
    float: left;
    margin-right: 3px;
}
</style>


<nav class="select  ">
    <li><a href="#">update</a></li>
    <li><a href="/requests">Request</a></li>
    <li><a href="/offers">BOARD</a></li>
    <li><a href="/offers/list">List</a></li>
</nav>
<h1>BOARD</h1>
<table class="container" cellpandding="0" cellspacing="0" border="0">
  <thead>
    <tr>
      <th><h1>Estado</h1></th>
      <th><h1>Agency</h1></th>
      <th><h1>KPI</h1></th>

      <th><h1>Price</h1></th>
      <th><h1>Geo</h1></th>
      <th><h1>Agencylink</h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td class="<%= offer.estado %>"><%= offer.estado %></td>
        <td class="<%= offer.estado %>"><%= offer.agency %></td>
        <td class="<%= offer.estado %>"> <%= offer.kpi %></td>
        <td class="<%= offer.estado %>"> <%= offer.price %></td>
        <td class="<%= offer.estado %>"> <%= offer.geo %></td>
        <td class="<%= offer.estado %>"> <%= offer.agencyLink %></td>

        <td class="<%= offer.estado %>"><div class="btn-group ">
          <input class="button aprobado" type="submit" onclick = "location='/offers/<%= offer.id %>/aprobado'" value="✔" />
          <input class="button rechazado" type="submit" onclick = "location='/offers/<%= offer.id %>/no_aprobado'" value="✘" />
          <input class="button subido" type="submit" onclick = "location='/offers/<%= offer.id %>/subido'" value="↕" />
          <input class="button destroy" type="submit" onclick = "location='/offers/<%= offer.id %>/destruido'" value="D" />

        </div></td>
        <!-- <td><div class="btn-group">
          <button class="button">Button</button>
          <button class="button">Button</button>
          <button class="button">Button</button>
          <button class="button">Button</button>
        </div></td> -->
        <!-- <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Aprobado', approb_offer_path(offer) %></td>
        <td><%= link_to 'Rechazado', non_approb_offer_path(offer) %></td>
        <td><%= link_to 'Autorizado',authotized_offer_path(offer) %></td>
        <td><%= link_to 'No autorizado', non_authotized_offer_path(offer) %></td>
        <td><%= link_to 'Subido', upload_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="center">
  <%= render 'form', offer: @offer %>

</div>
</div>

app/views/offers/list.html.erb
<div class= "bg">
<p id="notice"><%= notice %></p>
<style>
.btn-group .button {
     /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    cursor: pointer;
    float: left;
    margin-right: 3px;
}
</style>

<div class="info">
  <div class="buttons">
    <p>
      <a href="#" data-modal="moda1" class="modal__trigger">update</a>
      <a href="/requests">Request</a>
      <a href="/offers">BOARD</a>
      <a href="/offers/list">List</a>
    </p>

  </div>
</div>


<h1>LIST</h1>
<table class="container" cellpandding="0" cellspacing="0" border="0">
  <thead>
    <tr>
      <th><h1>Estado</h1></th>
      <th><h1>Agency</h1></th>
      <th><h1>Tipo</h1></th>
      <th><h1>App</h1></th>
      <th><h1>Os</h1></th>
      <th><h1>Geo</h1></th>
      <th><h1>Price</h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td class="<%= offer.estado %>"><%= offer.estado %></td>
        <td class="<%= offer.estado %>"><%= offer.agency %></td>
        <td class="<%= offer.estado %>"><%= offer.tipo %></td>
        <td class="<%= offer.estado %>"><%= offer.app %></td>
        <td class="<%= offer.estado %>"><%= offer.os %></td>
        <td class="<%= offer.estado %>"><%= offer.geo %></td>
        <td class="<%= offer.estado %>"><%= offer.price %></td>
        <td class="<%= offer.estado %>"><div class="btn-group ">
          <input class="button aprobado" type="submit" onclick = "location='/offers/<%= offer.id %>/monetizado'" value="$" />
          <input class="button afiliado" type="submit" onclick = "location='/offers/<%= offer.id %>/afiliado'" value="@ " />
          <input class="button rechazado" type="submit" onclick = "location='/offers/<%= offer.id %>/stop'" value="" />
          <input class="button destroy" type="submit" onclick = "location='/offers/<%= offer.id %>/destruido'" value="D" />

        </div></td>

        <!-- <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Afliado', afiliate_offer_path(offer) %></td>
        <td><%= link_to 'Monetizado', monetized_offer_path(offer) %></td>
        <td><%= link_to 'Stop', stop_offer_path(offer) %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th>Agency</th>
      <th>Tipo</th>
      <th>App</th>
      <th>Os</th>
      <th>Geo</th>
      <th>Price</th>
      <th>Agencylink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offersI.each do |offer| %>
      <tr>
        <td><%= offer.estado %></td>
        <td><%= offer.agency %></td>
        <td><%= offer.tipo %></td>
        <td><%= offer.app %></td>
        <td><%= offer.os %></td>
        <td><%= offer.geo %></td>
        <td><%= offer.price %></td>
        <td><%= offer.agencyLink %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @offer.estado %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @offer.agency %>
</p>

<p>
  <strong>tipo:</strong>
  <%= @offer.tipo %>
</p>

<p>
  <strong>App:</strong>
  <%= @offer.app %>
</p>

<p>
  <strong>Os:</strong>
  <%= @offer.os %>
</p>

<p>
  <strong>Geo:</strong>
  <%= @offer.geo %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<p>
  <strong>Agencylink:</strong>
  <%= @offer.agencyLink %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estado %>
    <%= f.text_field :estado %>
  </div>

  <div class="field">
    <%= f.label :agency %>
    <%= f.text_field :agency %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :app %>
    <%= f.text_field :app %>
  </div>

  <div class="field">
    <%= f.label :os %>
    <%= f.text_field :os %>
  </div>

  <div class="field">
    <%= f.label :geo %>
    <%= f.text_field :geo %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :agencyLink %>
    <%= f.text_field :agencyLink %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<div class= "bg">
<p id="notice"><%= notice %></p>
<nav class="select  ">
    <li><a href="#">update</a></li>
    <li><a href="/requests">Request</a></li>
    <li><a href="/offers">Board</a></li>
    <li><a href="/offers/list">List</a></li>
</nav>



<h1>REQUEST</h1>
<table class="container" cellpandding="0" cellspacing="0" border="0">
  <thead>
    <tr>
      <th><h1>Agency</h1></th>
      <th><h1>Tipo</h1></th>
      <th><h1>App</h1></th>
      <th><h1>Os</h1></th>
      <th><h1>Geo</h1></th>
      <th><h1>Price</h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.estado %></td>
        <td><%= request.agency %></td>
        <td><%= request.tipo %></td>
        <td><%= request.app %></td>
        <td><%= request.os %></td>
        <td><%= request.geo %></td>
        <td><%= request.price %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="center">
  <%= render 'form', request: @request %>

</div>
</div>

app/views/requests/new.html.erb
<h1>New Request</h1>

<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th>Agency</th>
      <th>Tipo</th>
      <th>App</th>
      <th>Os</th>
      <th>Geo</th>
      <th>Price</th>
      <th>Agencylink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requestsI.each do |request| %>
      <tr>
        <td><%= request.estado %></td>
        <td><%= request.agency %></td>
        <td><%= request.tipo %></td>
        <td><%= request.app %></td>
        <td><%= request.os %></td>
        <td><%= request.geo %></td>
        <td><%= request.price %></td>
        <td><%= request.agencyLink %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @request.estado %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @request.agency %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @request.tipo %>
</p>

<p>
  <strong>App:</strong>
  <%= @request.app %>
</p>

<p>
  <strong>Os:</strong>
  <%= @request.os %>
</p>

<p>
  <strong>Geo:</strong>
  <%= @request.geo %>
</p>

<p>
  <strong>Price:</strong>
  <%= @request.price %>
</p>

<p>
  <strong>Agencylink:</strong>
  <%= @request.agencyLink %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>